### ISSUE TITLE
Request for adding three of my papers relevant to auditing/verification

### ISSUE THREAD

**Issue by infinite-pursuits** [erwanlemerrer/awesome-audit-algorithms#7]
1. [FairProof: Confidential and Certifiable Fairness for Neural Networks](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=-fhMN10AAAAJ&sortby=pubdate&authuser=1&citation_for_view=-fhMN10AAAAJ:u5HHmVD_uO8C) (2024)

2. [Keeping Up with the Language Models: Robustness-Bias Interplay in NLI Data and Models](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=-fhMN10AAAAJ&sortby=pubdate&authuser=1&citation_for_view=-fhMN10AAAAJ:9yKSN-GCB0IC) (2023)

3. [XAudit: A Theoretical Look at Auditing with Explanations](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=-fhMN10AAAAJ&sortby=pubdate&authuser=1&citation_for_view=-fhMN10AAAAJ:zYLM7Y9cAGgC) (2023)

**Comment by erwanlemerrer** [comment]
hello, yes of course, can you include them in a pull request ? that is the intended process of awesome lists thanks

**Comment by infinite-pursuits** [comment]
got it thanks.. submitted a pr
